# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/msg/TypeDef.msg"
services_str = "/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/DeleteParam.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/GetActionServers.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/GetParam.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/GetParamNames.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/GetTime.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/HasParam.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/MessageDetails.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/Nodes.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/NodeDetails.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/Publishers.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/SearchParam.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServiceHost.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServiceNode.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServiceProviders.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServiceRequestDetails.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServiceResponseDetails.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/Services.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServicesForType.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/ServiceType.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/SetParam.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/Subscribers.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/Topics.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/TopicsAndRawTypes.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/TopicsForType.srv;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/srv/TopicType.srv"
pkg_name = "rosapi"
dependencies_str = ""
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "rosapi;/home/waqas/rosbridge_ws/src/rosbridge_suite/rosapi/msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = 'TRUE' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
